### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by Segrel** [jkotima/travelleri#1]
# Koodikatselmointi

Projekti kloonattu perjantaina 27.10. uusimman muutoksen ollessa 0accbcae19caae6c032ca75145122ba909129276.

Yleisesti ottaen ydintoiminnallisuus näyttää olevan hyvin kasassa ja toteutus selkeää!

## Työkalut

Projektissa ei määritelty tuettua java-versiota, testasin käyttäen OpenJDK 15. `./gradlew build` ei puhtaalta pöydältä ajautunut jacocoon liittyvien virheiden johdosta. Lisäämällä `build.gradle`-tiedostoon eksplisiittinen versiomäärittely 0.8.6 (jossa tuki Java 15) ongelma korjaantui:
```
jacoco {
    toolVersion = "0.8.6"
}
```
`./gradlew jacocoTestReport` toimi ja `./gradlew javadoc` generoi onnistuneesti Javadocin, joskin muutaman puuttuvista kommenteista huomauttavan tulosterivin kera.

## Ohjelman kokeilu

Kokeilin luoda verkon ja tallentaa sen tiedostoon, sekä avata verkon ja analysoida sen annetuilla vaihtoehdoilla. Vaihtoehto kolme eli suorituskykytestit sulki sovelluksen tekemättä mitään.

Kokeilin myös muutaman projektin mukana tulleen testi-csv:n kanssa jolloin sovellus antoi odotetun oloisia tuloksia!

## Projektin rakenne

Projektin hakemistorakenne on varsin pelkistetty ja selkeä. Ehkä `tests` hakemiston sisältö ei vastannut ensioletusta, tälle ehkä miettisin toista nimeä. `.gitignore.save` tiedosto on ehkäpä turha koko projektissa?

## Koodi

Domain-luokat vaikuttavat varsin siisteiltä ja toteuttavat näppärästi yhteisen protokollan. Toteutukset vaikuttavat selkeiltä, koodi luettavalta ja luokat järkevästi rajatuilta.

Käyttöliittymä ja muu oheinen ei ole välttämättä niin suuressa roolissa tällaisessa projektissa, mutta jos näitä haluaa parantaa, niin esimerkiksi ConsoleUI-luokkaa voisi siistiä ja palastella ehkä useampaankin eri luokkaan. Tämä tuntui itselleni ehkäpä selkeimmin suorituskykytestauksen logiikan löytyessä ConsoleUI tiedostosta.

## Testit

Yksikkötestaus vaikuttaa varsin kattavalta, kiinnitin huomiota lähinnä DtspMemo-luokan testaukseen, jossa vaikkapa `exists` metodin testaus voisi kattavammin käydä läpi oletetun rajapinnan oikeellisuutta eri tapauksissa.

Koitin miettiä myös käänteisesti voisiko jotain poistaa ja jäin pohtimaan `knownBigGraph` testejä joillain TSP-luokilla. Nämä siis sinänsä tuntuvat toisteisilta kun on jo testattu toimivuus jollain graafilla ja esimerkiksi NaiveTSPTest ei sisällä tällaista testiä. Toisaalta näidenkään suoritus ei tunnu kauaa kestävän ja taustalla saattoi olla myös jokin ajatus jota en omasta vinkkelistäni hahmota.

Hyvä!

**Comment by jkotima** [comment]
Kiitos näistä!
